name: Periodic Workflow

on:
  schedule:
    - cron: '*/20 1 * * 0-4'

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
       - run: echo ${{ github.repository }}
       - run: echo ${{ runner.name }}       
       - run: echo ${{ runner.os }}